---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: skip-ci
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: commit-message
      default: ""
    - name: pipeline-debug
      default: "0"
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: clone-task
      taskRef:
        name: git-clone-repo
      conditions:
        - conditionRef: skip-ci
          params:
            - name: commit-message
              value: $(params.commit-message)
      workspaces:
        - name: output
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
